import './globals.css';
import './page.module.css';
import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import { AppThemeProvider } from '@/providers';
// font
const spaceGrotesk = Space_Grotesk({
  variable: '--space-grotesk',
  subsets: ['latin'],
});
// metadata
export const metadata: Metadata = {
  title: 'Paynex',
  description: 'Generated by create next app',
};
// root
export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={spaceGrotesk.variable}>
      <AppThemeProvider>
        <body>
          { children }
        </body>
      </AppThemeProvider>
    </html>
  );
};